CREATE TABLE hr.manager (
    "id"          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        VARCHAR2(100) NOT NULL,
    "age"         NUMBER(3),
    "birth_date"  DATE,
    "address"     VARCHAR2(255)
);
