CREATE TABLE hr.doctor (
    "id"       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"     VARCHAR2(100) NOT NULL,
    "salary"   NUMBER(10,2),
    "address"  VARCHAR2(100) NOT NULL
);
