CREATE TABLE hr."employees" (
    "EmployeeID"   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName"    VARCHAR2(100) NOT NULL,
    "LastName"     VARCHAR2(100) NOT NULL,
    "Department"   VARCHAR2(50),
    "Salary"       NUMBER(10,2)
);
